package com.example.demo.enums;

public enum NotificationType {
    POST,
    FOLLOW_RESPONSE,
    FOLLOW_REQUEST,
    COMMENT,
    REPLY_COMMENT,
    MESSAGE,
    GROUP_INVITATION,
    GROUP_MEMBERSHIP_REQUEST,
    GROUP_MEMBERSHIP_RESPONSE,
    POST_REACTION,
    GROUP_ADD_MEMBER,
    POST_APPROVAL,
    POST_REJECTION,
}
